# Read the Docs configuration file for Sphinx projects
version: 2

# Set the OS, Python version
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

# Python requirements
python:
  install:
  - requirements: docs/requirements.txt

# Build documentation in the "docs/" directory with Sphinx
sphinx:
  configuration: docs/conf.py
